services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: GCP_SERVICE_ACCOUNT_JSON
        sync: false
